### ISSUE TITLE
Subdocuments Array has not id() and remove()-method

### ISSUE THREAD

**Issue by gerritlo** [nestjs/mongoose#1718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I have a schema with a subdocument array schema I can't access a subdocument via` id()`-function or remove it with the `remove()`-function

### Minimum reproduction code

https://gist.github.com/gerritlo/bd78ed72c8612e0a8662a81361952b7a

### Expected behavior

On subdocuments array-property of the parent document an `id()` function is existing
[Mongoose docs](https://mongoosejs.com/docs/subdocs.html#removing-subdocs)

### Package version

9.2.1

### mongoose version

6.9.1

### NestJS version

9.3.8

### Node.js version

16.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by gerritlo** [comment]
Added a mongoose example that works as expected to the gist

**Comment by jmcdo29** [comment]
This is how _Typescript_ works. You say that `payments` is of type `PaymentDetails[]` and you're surprised when there are not mongoose related methods even though your class doesn't have those mongoose methods or extend the mongoose types. Probably you should be using `PaymentDetailsDocument[]` instead, so that it is your type _plus_ the mongoose document type

**Comment by gerritlo** [comment]
Posted the solution that works for me here: https://stackoverflow.com/questions/75756488/how-to-push-subdocument-to-mongoose-model-with-typescript/75778521#75778521

**Comment by ubugnu** [comment]
Add a second hydrated document that represents the list:
```js
