### ISSUE TITLE
Initial Connection Error Handling

### ISSUE THREAD

**Issue by tomwanzek** [nestjs/mongoose#6]
First of all, thanks for the great job on nestjs and its ecosystem 🥇 

That being said, given that the connection to the MongoDB instance is initially established in the `forRoot(...)` method, what is the recommended approach to catching and handling an initial connection error?

**Comment by kamilmysliwiec** [comment]
Thanks @tomwanzek! In the nearest update there'll be a retrying strategy applied by default, but still, there's no built-in way to handle a connection error directly from the module options. In order to have a little bit more flexibility, you can always create this simple module on your own as explained here https://docs.nestjs.com/recipes/mongodb 🙂

**Comment by pumano** [comment]
I also waiting for that feature, because I need to throw custom 500 error exception when connection is not established.

**Comment by aldorea** [comment]
Are there other ways to customize mongo errors like execption filter?
