### ISSUE TITLE
Request scoped connections

### ISSUE THREAD

**Issue by osmirnov** [nestjs/mongoose#65]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
The connection is created as a singleton

## Expected behavior
The connection options support `scope` (https://docs.nestjs.com/fundamentals/injection-scopes) to be defined as per request.

## What is the motivation / use case for changing the behavior?
I'd like to open an isolated connection on every HTTP requests.

## Environment
<pre><code>
Nest version: 6.1.2

 </code></pre>

**Comment by kamilmysliwiec** [comment]
Great idea. We'll surely implement this at some point.

For those who are looking for a workaround, you can always create your own `MongooseModule` like described here: https://docs.nestjs.com/recipes/mongodb

**Comment by DenisPalchuk** [comment]
Is it a good idea to provide new connection per request? Let's check docs: 
http://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html#mongoclient-connection-pooling
As you can see mongo driver created connection pool under the hood after init app and provided db object for sharing it across app. Creating connection pool per request is a bad idea. 
As a workaround we can use mongo transactions (which work only with 4.x version and only with replica set) + CLS.

**Comment by aneudysamparo** [comment]
@DenisPalchuk I think this may depends on the case!
For me I'd like to use a different DB depending on the request (subdomain). Just trying to make a multi-tenancy app based on domain/subdomain names.

currently i could this make it work but using MongooseModule and mongoose lib per-sé, which I think is a big force!

Check this!
[Database Provider - set database dynamically based on subdomain using just mongoose](https://github.com/aneudysamparo/cat-book-api/blob/initialCommit/src/common/databases/database.providers.ts)

But here in same project i used NestJS MongooseModule because it doesn't have `scope` to provide REQUEST object.
[Tenant Module](https://github.com/aneudysamparo/cat-book-api/blob/initialCommit/src/common/tenants/tenant.module.ts)

I'd like to use just NestJS MongooseModule with custom provider (`scope`)

What do you think?

**Comment by AliYusuf95** [comment]
I need this feature too.

I think the `Provider` should be smart enough to eather to use an existing connection or generate a new connection to the requested database if the connection is not initiated before.

**Comment by AliYusuf95** [comment]
I did a [simple implementation](https://gist.github.com/AliYusuf95/e7faa722d82426008e90b44206a50000) for [nest-mongodb](https://github.com/erikc5000/nest-mongodb), please check it out

The main changes are in `mongo-core.module.ts` where I store the connections in a map and used them if available instead of creating a new connection every time.

I test it and it works with Request scoped `MongooseOptionsFactory` for the DB Module

**Comment by MarluanEspiritusanto** [comment]
@AliYusuf95 Can you implement your solution in the @nestjs/mongoose module?

**Comment by sandeepsuvit** [comment]
> @DenisPalchuk I think this may depends on the case!
> For me I'd like to use a different DB depending on the request (subdomain). Just trying to make a multi-tenancy app based on domain/subdomain names.
> 
> currently i could this make it work but using MongooseModule and mongoose lib per-sé, which I think is a big force!
> 
> Check this!
> [Database Provider - set database dynamically based on subdomain using just mongoose](https://github.com/aneudysamparo/cat-book-api/blob/initialCommit/src/common/databases/database.providers.ts)
> 
> But here in same project i used NestJS MongooseModule because it doesn't have `scope` to provide REQUEST object.
> [Tenant Module](https://github.com/aneudysamparo/cat-book-api/blob/initialCommit/src/common/tenants/tenant.module.ts)
> 
> I'd like to use just NestJS MongooseModule with custom provider (`scope`)
> 
> What do you think?

Small update to this solution which is similar to what i followed

```typescript
import * as mongoose from 'mongoose';
import { Connection } from 'mongoose';
import { REQUEST } from '@nestjs/core';
import { Scope, NotFoundException } from '@nestjs/common';
import { TenantsService } from '../tenants/tenant.service';


export const databaseProviders = [
    {
        provide: 'DATABASE_CONNECTION',
        scope: Scope.REQUEST,
        useFactory: async (req, tenants: TenantsService): Promise<typeof mongoose> => {
            if (req.subdomains[0] && req.subdomains[0] !== undefined && req.subdomains[0] !== 'undefined') {
                const tenantDB: string = req.subdomains[0];
                let foundTenant = await tenants.findOne({ subdomain: tenantDB });
                if (!foundTenant) {
                    throw new NotFoundException('AppName does not exits');
                }
                // Check if is actived
                console.log(foundTenant);

                // Get the underlying mongoose connections
                const connections: Connection[] = mongoose.connections;

                // Find existing connection
                const foundConn = connections.find((con: Connection) => {
                    return con.name === tenantDB;
                });

                // Return the same connection if it exist
                if (foundConn && foundConn.readyState === 1) {
                    return foundConn;
                }

                return mongoose.connect(`mongodb://localhost/${foundTenant.tenantdb}`, { useNewUrlParser: true });
            } else {
                return mongoose.connect(`mongodb://localhost/TodoAppDB`, { useNewUrlParser: true });
            }
        },
        inject: [REQUEST, TenantsService]
    }
];
```

**Comment by MarluanEspiritusanto** [comment]
I've made a PR that contributes to this feature request, you can see at: https://github.com/nestjs/mongoose/pull/229

**Comment by sandeepsuvit** [comment]
Hi @MarluanEspiritusanto can you please provide an example reference on how to use it.

**Comment by adriano-di-giovanni** [comment]
I've just published a [gist](https://gist.github.com/adriano-di-giovanni/8c3e1069c5a14d947773c64c41501bd6) of a multi-tenant mongoose module for nest.

I'm relatively new to Nest and I'd like to have your feedback.

@kamilmysliwiec is that something valid?

**Comment by kamilmysliwiec** [comment]
It looks great at first sight :) @adriano-di-giovanni

**Comment by sandeepsuvit** [comment]
@adriano-di-giovanni Thats a nice implementation. Would love to see an article about it like @kamilmysliwiec said, as many of us are waiting for an approach on Multi-tenancy using Nestjs. 

I have tried multiple approaches on this using `REQUEST` scope (to extract the TENANT_ID), but the issue i faced while using `REQUEST` scope is that the passport module wont work since they are global scoped.

**Comment by sandeepsuvit** [comment]
I have put together a library based on @adriano-di-giovanni gist and made some modifications to it. Here is the repository [nest-tenancy](https://github.com/needle-innovision/nestjs-tenancy). Would love to hear your comments on it @kamilmysliwiec 
And thanks @adriano-di-giovanni for your gist, which really helped :)

**Comment by dryize** [comment]
I spent the whole day trying to figure out the best way to implement this. To try out I took the concept from @adriano-di-giovanni and lib from @sandeepsuvit and implemented a fully working solution. 
I was able to solve the issues with global auth guards, passport, graphql. You can check the source code from below git repo.
https://github.com/databoxtech/nestjs-multi_tenant-multiple-database

I've added two global guards, one for jwt auth and another to ensure tenancy. Both are applied at global level and ignore the /auth/login endpoint. For any other endpoint TenancyGuard will make sure tenancy present in header and the jwt token are equal. This takes away the vulnerability where you can access other tenants once you are logged into one by altering headers.

**Comment by AliYusuf95** [comment]
I had tried to implement this in several ways, but I don't fee it the right way to do it.
What I want to achieve the following:
- The module has a default connection.
- Fallback to the default connection if the request doesn't have a tenant connection.
- The connection should be reused whenever it's possible.
- Named connection feature (to force creation a different connection).
- Tenants connection configurations can be loaded from the base connection.
- Ability to inject the right connection seamlessly.
- Avoid `Scope.REQUEST` as much as possible (for efficiency).

The last two points which make things hard, they are critical to me since I don't want to recreate the services and all other components for each request -_it should be efficient_- and I won't use the right connection easily.

Since the request is only available in the controller and the previous stages, without having `Scope.REQUEST` or passing it as a parameter, the connections can be created in an `interceptor` for example -_so we can use `req.user` from passport to get the tenant_- and store it in a connection store, then this store can be used in the other services.

But the usage of the connection will not we seamlessly like what this library offers, where the mongoose model is injected directly in the service instead of the connections store. Also, we have to pass the (request/user/tenant ref) to the service if we want to avoid the `Scope.REQUEST`.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
